"""empty message

Revision ID: d20a84f2689b
Revises: 903ea3df5d28
Create Date: 2019-09-12 10:14:43.632977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd20a84f2689b'
down_revision = '903ea3df5d28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Shows', sa.Column('artist_name', sa.String(), server_default='select name from Venue where id = (no name)', nullable=True))
    op.add_column('Shows', sa.Column('venue_name', sa.String(), server_default='select name from Venue where id = (no name)', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Shows', 'venue_name')
    op.drop_column('Shows', 'artist_name')
    # ### end Alembic commands ###
